// Generates src/components/app/stamp-rim.ts: the stamp's rim texts («رابطة شباب قرية البقيع» on
// top, «صندوق الرابطة» below) as ready SVG outline paths along their arcs. SVG <textPath> does not
// shape Arabic in WebKit (iPhone Safari) and some Android WebViews (unjoined, reversed letters),
// so the texts are shaped once here with HarfBuzz and committed as path data.
//
// Not a project dependency; run it only when the texts, the arcs or the font change:
//   mkdir -p /tmp/rim && cp scripts/stamp-rim.mjs /tmp/rim && cd /tmp/rim && npm i harfbuzzjs
//   curl -sLo Alexandria.ttf "https://github.com/google/fonts/raw/main/ofl/alexandria/Alexandria%5Bwght%5D.ttf"
//   node stamp-rim.mjs Alexandria.ttf <repo>/src/components/app/stamp-rim.ts
import fs from "node:fs";
import * as hb from "harfbuzzjs";

const [FONT, OUT] = process.argv.slice(2);
if (!FONT || !OUT) throw new Error("usage: node stamp-rim.mjs <Alexandria[wght].ttf> <out.ts>");

/** Same geometry as <Stamp>: viewBox 200, Alexandria 700 at 13 px, centred on each arc. */
const C = 100;
const SIZE = 13;
const RIMS = [
  { name: "RIM_TOP", text: "رابطة شباب قرية البقيع", r: 73.45, top: true },
  { name: "RIM_BOTTOM", text: "صندوق الرابطة", r: 79.15, top: false },
];

const data = fs.readFileSync(FONT);
const face = new hb.Face(
  new hb.Blob(data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength)),
);
const font = new hb.Font(face);
font.setVariations([hb.Variation.fromString("wght=700")]);
const k = SIZE / face.upem;

const num = (n) => {
  const s = n.toFixed(2).replace(/\.?0+$/, "");
  return s === "-0" ? "0" : s;
};

/** Font-unit path (y up) → absolute SVG path through the matrix [a b c d e f]. */
function place(d, [a, b, c, dd, e, f]) {
  const tokens = d.match(/[MLQCZ]|-?\d*\.?\d+(?:e-?\d+)?/gi) ?? [];
  let out = "";
  let cmd = "";
  const xs = [];
  for (const t of tokens) {
    if (/^[MLQCZ]$/i.test(t)) {
      cmd = t.toUpperCase();
      out += cmd;
      continue;
    }
    xs.push(Number(t));
    if (xs.length === 2) {
      const [x, y] = xs.splice(0, 2);
      out += `${num(a * x + c * y + e)} ${num(b * x + dd * y + f)} `;
    }
  }
  return out.replace(/ ([MLQCZ])/g, "$1").trim();
}

function rim({ text, r, top }) {
  const buf = new hb.Buffer();
  buf.addText(text);
  buf.guessSegmentProperties();
  hb.shape(font, buf);
  const glyphs = buf.getGlyphInfosAndPositions(); // visual order, left to right
  const total = glyphs.reduce((s, g) => s + g.xAdvance, 0) * k;
  // like textPath startOffset=50% text-anchor=middle: each glyph's middle on the arc, upright
  let pen = (Math.PI * r) / 2 - total / 2;
  let d = "";
  for (const g of glyphs) {
    const adv = g.xAdvance * k;
    const s = pen + adv / 2;
    const th = top ? Math.PI - s / r : Math.PI + s / r;
    const px = C + r * Math.cos(th);
    const py = C - r * Math.sin(th);
    const rot = top ? Math.PI / 2 - th : (3 * Math.PI) / 2 - th;
    const cos = Math.cos(rot);
    const sin = Math.sin(rot);
    const ox = -adv / 2 + g.xOffset * k;
    const oy = -g.yOffset * k;
    // translate(px,py) · rotate(rot) · translate(ox,oy) · scale(k,−k)
    const m = [
      cos * k,
      sin * k,
      sin * k,
      -cos * k,
      px + cos * ox - sin * oy,
      py + sin * ox + cos * oy,
    ];
    d += place(font.glyphToPath(g.codepoint), m);
    pen += adv;
  }
  return d;
}

const body = RIMS.map(
  (x) =>
    `/** «${x.text}» on the arc r${x.r} (${x.top ? "top" : "bottom"}). */\nexport const ${x.name} =\n  "${rim(x)}";`,
).join("\n\n");
fs.writeFileSync(
  OUT,
  `// GENERATED by scripts/stamp-rim.mjs (Alexandria 700, HarfBuzz). Do not edit by hand.\n// The stamp's rim texts as outline paths: <textPath> breaks Arabic in WebKit.\n\n${body}\n`,
);
console.log("wrote", OUT);
