// Fictional data for the 10 committee reports (tests, demo previews). Names are made up.
import type {
  AnnualReport,
  CampaignReport,
  CommitteeWorkReport,
  DonationStats,
  ExpensesReport,
  FeeStats,
  GridReport,
  HandoverReport,
  LateReport,
  LevyStats,
  MemberStatement,
  StatsReport,
  SummaryReport,
  WalletsReport,
} from "../data/report-types";
import type { ReportMonthState } from "../data/types";

const AT = "2026-09-28T10:00:00.000Z";
const NAMES = [
  "محمد ولد الشيخ",
  "أحمد ولد سيدي",
  "سيدي محمد ولد أحمد",
  "الحسن ولد عبد الله",
  "المختار ولد محمد",
  "عالي ولد الشيخ",
  "الداه ولد سيدي",
  "باب ولد عبد الله",
  "محمدو ولد محمد",
  "يحيى ولد الشيخ",
  "عبد الرحمن ولد سيدي",
  "الطالب ولد أحمد",
];
const monthsPaid = (n: number): ReportMonthState[] =>
  Array.from({ length: 12 }, (_, k) => (k < n ? "paid" : k < 9 ? "late" : "upcoming"));

export const fxAnnual: AnnualReport = {
  period: { year: 2026 },
  generatedAt: AT,
  opening: 120_000,
  income: { fees: 212_500, levies: 30_000, donations: 71_000, total: 313_500 },
  spending: {
    byCategory: [
      { category: "teaching", label: "التدريس", amount: 90_000 },
      { category: "sports", label: "الرياضة", amount: 18_500 },
      { category: "honoring", label: "التكريم", amount: 25_000 },
    ],
    fromCampaigns: 25_000,
    total: 133_500,
  },
  adjustments: 0,
  closing: 300_000,
  campaignsHeld: 46_000,
  months: Array.from({ length: 12 }, (_, k) => ({
    year: 2026,
    month: k + 1,
    income: k < 9 ? [41_000, 30_500, 28_000, 26_000, 24_500, 22_000, 21_500, 60_000, 60_000][k] : 0,
    spending: k < 9 ? [0, 15_000, 0, 30_000, 0, 18_500, 0, 45_000, 25_000][k] : 0,
  })),
};

export const fxSummary: SummaryReport = {
  period: { year: 2026, month: 9 },
  generatedAt: AT,
  opening: 265_000,
  income: 60_000,
  spending: 25_000,
  closing: 300_000,
  membersActive: 89,
  membersPaidPeriod: 47,
  membersLate: 42,
  openCampaigns: 1,
  openLevies: 1,
};

export const fxGrid: GridReport = {
  year: 2026,
  generatedAt: AT,
  groupPrices: { A: 1000, B: 500 },
  members: NAMES.map((n, i) => ({
    memberRef: `${i < 7 ? "A" : "B"}-${i + 1}`,
    fullName: n,
    groupCode: i < 7 ? "A" : "B",
    status: "active",
    statusLabel: "",
    months: monthsPaid([12, 9, 9, 0, 5, 0, 9, 3, 12, 9, 0, 6][i]),
    monthsPaid: [12, 9, 9, 0, 5, 0, 9, 3, 12, 9, 0, 6][i],
    monthsBehind: 0,
  })),
};

export const fxLate: LateReport = {
  year: 2026,
  generatedAt: AT,
  members: [
    {
      memberRef: "A-4",
      fullName: "الحسن ولد عبد الله",
      groupCode: "A",
      lateMonths: [
        "2026-01",
        "2026-02",
        "2026-03",
        "2026-04",
        "2026-05",
        "2026-06",
        "2026-07",
        "2026-08",
        "2026-09",
      ],
      monthsCount: 9,
      levies: [{ title: "ترميم المسجد" }],
    },
    {
      memberRef: "A-5",
      fullName: "المختار ولد محمد",
      groupCode: "A",
      lateMonths: ["2026-06", "2026-07", "2026-08", "2026-09"],
      monthsCount: 4,
      levies: [],
    },
    {
      memberRef: "B-8",
      fullName: "باب ولد عبد الله",
      groupCode: "B",
      lateMonths: ["2026-04", "2026-05", "2026-06", "2026-07", "2026-08", "2026-09"],
      monthsCount: 6,
      levies: [],
    },
    {
      memberRef: "B-11",
      fullName: "عبد الرحمن ولد سيدي",
      groupCode: "B",
      lateMonths: [],
      monthsCount: 0,
      levies: [{ title: "ترميم المسجد" }],
    },
  ],
};

export const fxExpenses: ExpensesReport = {
  period: { year: 2026 },
  generatedAt: AT,
  items: [
    {
      spentOn: "2026-09-17",
      category: "sports",
      label: "الرياضة",
      note: "كرات وأقمصة",
      amount: 18_500,
      campaignTitle: null,
      recordedBy: "يحيى",
    },
    {
      spentOn: "2026-08-20",
      category: "teaching",
      label: "التدريس",
      note: "راتب المعلم",
      amount: 45_000,
      campaignTitle: null,
      recordedBy: "سيدي محمد",
    },
    {
      spentOn: "2026-08-02",
      category: "honoring",
      label: "التكريم",
      note: "إسمنت ورمل",
      amount: 25_000,
      campaignTitle: "ترميم المسجد",
      recordedBy: "سيدي محمد",
    },
    {
      spentOn: "2026-04-10",
      category: "teaching",
      label: "التدريس",
      note: null,
      amount: 45_000,
      campaignTitle: null,
      recordedBy: "يحيى",
    },
  ],
  byCategory: [
    { category: "teaching", label: "التدريس", amount: 90_000 },
    { category: "honoring", label: "التكريم", amount: 25_000 },
    { category: "sports", label: "الرياضة", amount: 18_500 },
  ],
  total: 133_500,
};

export const fxCampaign: CampaignReport = {
  generatedAt: AT,
  id: "c1",
  title: "ترميم المسجد",
  kind: "donation",
  purpose: "إصلاح سقف المسجد وطلاء الجدران.",
  status: "open",
  targetAmount: 300_000,
  createdAt: "2026-06-01",
  closedAt: null,
  collected: 71_000,
  spent: 25_000,
  transferred: 0,
  balance: 46_000,
  contributions: [
    { paidOn: "2026-09-20", name: "محمد ولد الشيخ", memberRef: "A-1", amount: 20_000 },
    { paidOn: "2026-08-11", name: "فاعل خير", memberRef: null, amount: 50_000 },
    { paidOn: "2026-06-05", name: "يحيى ولد الشيخ", memberRef: "B-10", amount: 1_000 },
  ],
  expenses: [{ spentOn: "2026-08-02", note: "إسمنت ورمل", amount: 25_000 }],
};

export const fxLevy: CampaignReport = {
  generatedAt: AT,
  id: "l1",
  title: "لوحة العيد",
  kind: "levy",
  purpose: null,
  status: "open",
  targetAmount: null,
  createdAt: "2026-05-01",
  closedAt: null,
  collected: 6_000,
  spent: 0,
  transferred: 0,
  balance: 6_000,
  contributions: [],
  expenses: [],
  shares: NAMES.slice(0, 5).map((n, i) => ({
    memberRef: `A-${i + 1}`,
    fullName: n,
    expected: 2_000,
    paid: i < 3 ? 2_000 : 0,
    left: i < 3 ? 0 : 2_000,
    exempt: i === 4,
    exemptReason: i === 4 ? "طالب" : null,
  })),
};

export const fxStatement: MemberStatement = {
  generatedAt: AT,
  year: 2026,
  member: {
    memberId: "m1",
    memberRef: "A-5",
    fullName: "المختار ولد محمد",
    groupCode: "A",
    status: "active",
    phone: null,
  },
  months: Array.from({ length: 12 }, (_, k) => ({
    month: k + 1,
    state: k < 5 ? "paid" : k < 9 ? "late" : "upcoming",
    price: 1000,
    paid: k < 5,
    due: k < 9,
  })),
  payments: [
    {
      paymentId: "p1",
      paidOn: "2026-03-02",
      status: "confirmed",
      method: "bankily",
      amount: 3000,
      total: 3000,
      months: ["2026-01", "2026-02", "2026-03"],
      campaigns: [],
      note: null,
      reason: null,
      recordedBy: "سيدي محمد",
      recordedAt: "2026-03-02T09:00:00Z",
      confirmedBy: "يحيى",
      confirmedAt: "2026-03-02T10:00:00Z",
      cancelledBy: null,
      cancelledAt: null,
    },
    {
      paymentId: "p2",
      paidOn: "2026-05-20",
      status: "confirmed",
      method: "cash",
      amount: 2000,
      total: 2000,
      months: ["2026-04", "2026-05"],
      campaigns: [],
      note: null,
      reason: null,
      recordedBy: "يحيى",
      recordedAt: "2026-05-20T09:00:00Z",
      confirmedBy: "يحيى",
      confirmedAt: "2026-05-20T09:00:00Z",
      cancelledBy: null,
      cancelledAt: null,
    },
    {
      paymentId: "p3",
      paidOn: "2026-06-01",
      status: "cancelled",
      method: "cash",
      amount: 1000,
      total: 1000,
      months: ["2026-06"],
      campaigns: [],
      note: null,
      reason: "سُجّلت مرتين",
      recordedBy: "يحيى",
      recordedAt: "2026-06-01T09:00:00Z",
      confirmedBy: null,
      confirmedAt: null,
      cancelledBy: "سيدي محمد",
      cancelledAt: "2026-06-01T12:00:00Z",
    },
  ],
  levies: [{ title: "لوحة العيد", expected: 2000, paid: 0, left: 2000, exempt: false }],
  owed: { monthsCount: 4, amountOwed: 4000, levyLeft: 2000, credit: 0 },
};

export const fxHandover: HandoverReport = {
  generatedAt: AT,
  term: { number: 2, title: "الدورة 2", startedOn: "2026-01-01", endedOn: null },
  opening: 120_000,
  income: fxAnnual.income,
  spending: fxAnnual.spending,
  adjustments: 0,
  computedBalance: 300_000,
  counted: [
    { label: "بنكيلي", method: "bankily", amount: 150_000 },
    { label: "مصرفي", method: "masrvi", amount: 80_000 },
    { label: "نقدًا لدى أمين الصندوق", method: "cash", amount: 70_000 },
  ],
  countedTotal: 300_000,
  difference: 0,
  startedBy: { name: "سيدي محمد", at: "2026-09-28T10:00:00Z" },
  submittedBy: { name: "سيدي محمد", at: null },
  acceptedBy: { name: null, at: null },
  carryOver: ["تبرع «ترميم المسجد» ما زال مفتوحًا.", "لوحة العيد: بقي عضوان لم يدفعا."],
};

export const fxWallets: WalletsReport = {
  period: { year: 2026 },
  generatedAt: AT,
  wallets: [
    { method: "bankily", label: "بنكيلي", accountNumber: "22000001", in: 145_000, count: 98 },
    { method: "masrvi", label: "مصرفي", accountNumber: "22000002", in: 70_000, count: 41 },
    { method: "sedad", label: "السداد", accountNumber: null, in: 23_500, count: 12 },
  ],
  cash: { in: 75_000, count: 60 },
  totalIn: 313_500,
};

export const fxWork: CommitteeWorkReport = {
  period: { year: 2026 },
  generatedAt: AT,
  people: [
    {
      name: "سيدي محمد",
      isAdmin: true,
      active: true,
      payments: { count: 31, amount: 58_500 },
      expenses: { count: 3, amount: 70_000 },
      cancellations: 1,
      levyExemptions: 1,
      lastAt: AT,
    },
    {
      name: "يحيى",
      isAdmin: false,
      active: true,
      payments: { count: 22, amount: 34_000 },
      expenses: { count: 0, amount: 0 },
      cancellations: 0,
      levyExemptions: 0,
      lastAt: AT,
    },
    {
      name: "المختار",
      isAdmin: false,
      active: false,
      payments: { count: 0, amount: 0 },
      expenses: { count: 0, amount: 0 },
      cancellations: 0,
      levyExemptions: 0,
      lastAt: null,
    },
  ],
  cancelled: [
    {
      what: "دفعة المختار ولد محمد",
      amount: 1000,
      by: "سيدي محمد",
      at: "2026-06-01T12:00:00Z",
      reason: "سُجّلت مرتين",
    },
  ],
};

/* «الإحصاءات»: counts only. 88 active members (A 40, B 48) in September 2026. */
const feeMonths = (year: number, refMonth: number, paid: number[]) =>
  paid.map((n, i) => ({
    month: i + 1,
    active: 88,
    paid: n,
    unpaid: i + 1 <= refMonth ? 88 - n : 0,
  }));
export const fxFeeStats: FeeStats = {
  year: 2026,
  refMonth: 9,
  asOf: null,
  beforeRecords: false,
  overall: { active: 88, paidUp: 42, paidUpPct: 47.7, owe1: 18, owe2to3: 16, owe4plus: 12 },
  groups: [
    { groupCode: "A", active: 40, paidUp: 22, paidUpPct: 55, owe1: 8, owe2to3: 6, owe4plus: 4 },
    { groupCode: "B", active: 48, paidUp: 20, paidUpPct: 41.7, owe1: 10, owe2to3: 10, owe4plus: 8 },
  ],
  months: feeMonths(2026, 9, [80, 78, 76, 74, 70, 66, 60, 52, 42, 5, 2, 2]),
};
export const fxLevyStats: LevyStats = {
  id: "l1",
  title: "لوحة العيد",
  status: "open",
  openedOn: "2026-09-18",
  daysOpen: 12,
  shares: 88,
  paid: 34,
  unpaid: 50,
  exempt: 4,
  paidPct: 40.5,
  expected: 168_000,
  collected: 68_000,
  groups: [
    {
      groupCode: "A",
      shares: 40,
      paid: 20,
      unpaid: 18,
      exempt: 2,
      paidPct: 52.6,
      expected: 76_000,
      collected: 40_000,
    },
    {
      groupCode: "B",
      shares: 48,
      paid: 14,
      unpaid: 32,
      exempt: 2,
      paidPct: 30.4,
      expected: 92_000,
      collected: 28_000,
    },
  ],
};
export const fxDonationStats: DonationStats = {
  id: "c1",
  title: "ترميم المصلى",
  status: "open",
  openedOn: "2026-06-01",
  memberGivers: 22,
  outsideGivers: 5,
  givers: 27,
  activeMembers: 88,
  memberPct: 25,
  collected: 64_000,
  target: 150_000,
  targetPct: 42.7,
};
export const fxStats: StatsReport = {
  period: { year: 2026 },
  generatedAt: AT,
  fees: fxFeeStats,
  previous: {
    ...fxFeeStats,
    year: 2025,
    asOf: "2025-09-30",
    overall: { ...fxFeeStats.overall, paidUp: 48, paidUpPct: 54.5 },
  },
  levies: [fxLevyStats],
  donations: [fxDonationStats],
};
