// Fictional data for the 10 committee reports (tests, demo previews). Names are made up.
import type {
  AnnualReport,
  CampaignReport,
  CommitteeWorkReport,
  DonationStats,
  ExpensesReport,
  FeeStats,
  GridReport,
  HandoverReport,
  LateReport,
  LevyStats,
  MemberStatement,
  StatsReport,
  SummaryReport,
  WalletsReport,
} from "../data/report-types";
import type { ReportMonthState } from "../data/types";

const AT = "2026-09-28T10:00:00.000Z";
const NAMES = [
  "محمد ولد الشيخ",
  "أحمد ولد سيدي",
  "سيدي محمد ولد أحمد",
  "الحسن ولد عبد الله",
  "المختار ولد محمد",
  "عالي ولد الشيخ",
  "الداه ولد سيدي",
  "باب ولد عبد الله",
  "محمدو ولد محمد",
  "يحيى ولد الشيخ",
  "عبد الرحمن ولد سيدي",
  "الطالب ولد أحمد",
];
const monthsPaid = (n: number): ReportMonthState[] =>
  Array.from({ length: 12 }, (_, k) => (k < n ? "paid" : k < 9 ? "late" : "upcoming"));

// The same fund as the demo app (src/components/app/fixtures.ts, server-only so not imported):
// opening 45 000, fees 376 500, the four expenses (127 500), the تبرع's 52 000 still held, so
// «منها في الصندوق» = home's «في الصندوق» 294 000. Levies 30 000 held too: total 376 000.
export const fxAnnual: AnnualReport = {
  period: { year: 2026 },
  generatedAt: AT,
  opening: 45_000,
  income: { fees: 376_500, levies: 30_000, donations: 52_000, total: 458_500, paper: 60_000 },
  spending: {
    byCategory: [
      { category: "teaching", label: "التدريس", amount: 60_000 },
      { category: "honoring", label: "التكريم", amount: 35_000 },
      { category: "sports", label: "الرياضة", amount: 28_000 },
      { category: "other", label: "أخرى", amount: 4_500 },
    ],
    byActivity: [
      { activityId: 1, name: "التدريس المحظري", amount: 60_000 },
      { activityId: 2, name: "تكريم الناجحين", amount: 35_000 },
      { activityId: 3, name: "الفريق الرياضي", amount: 28_000 },
      { activityId: 4, name: "أخرى", amount: 4_500 },
    ],
    fromCampaigns: 0,
    total: 127_500,
  },
  incomeDue: { total: 452_500, feesForOtherMonths: 6_000, feesPaidOutside: 0 },
  adjustments: 0,
  closing: 376_000,
  campaignsHeld: 82_000,
  months: Array.from({ length: 12 }, (_, k) => ({
    year: 2026,
    month: k + 1,
    income:
      k < 9 ? [48_000, 45_000, 44_000, 43_000, 42_500, 42_000, 40_000, 52_000, 102_000][k] : 0,
    // the same money by the month it pays for (6 000 of the fees are for 2027: not this year)
    dueIncome: [
      42_000, 41_500, 41_000, 40_500, 40_000, 39_500, 39_000, 38_500, 50_000, 27_000, 27_000,
      26_500,
    ][k],
    // the demo expenses by date: July 60 000, August 35 000 + 28 000, September 4 500
    spending: k < 9 ? [0, 0, 0, 0, 0, 0, 60_000, 63_000, 4_500][k] : 0,
  })),
};

export const fxSummary: SummaryReport = {
  period: { year: 2026, month: 9 },
  generatedAt: AT,
  // September of fxAnnual: ends on the same 376 000 (294 000 in the fund + 82 000 held)
  opening: 278_500,
  income: 102_000,
  incomePaper: 40_000,
  spending: 4_500,
  closing: 376_000,
  campaignsHeld: 82_000,
  membersActive: 89,
  membersPaidPeriod: 47,
  membersLate: 42,
  openCampaigns: 1,
  openLevies: 1,
};

export const fxGrid: GridReport = {
  year: 2026,
  generatedAt: AT,
  groupPrices: { A: 1000, B: 500 },
  members: NAMES.map((n, i) => ({
    memberRef: `${i < 7 ? "A" : "B"}-${i + 1}`,
    fullName: n,
    groupCode: i < 7 ? "A" : "B",
    status: "active",
    statusLabel: "",
    months: monthsPaid([12, 9, 9, 0, 5, 0, 9, 3, 12, 9, 0, 6][i]),
    monthsPaid: [12, 9, 9, 0, 5, 0, 9, 3, 12, 9, 0, 6][i],
    monthsBehind: 0,
  })),
};

export const fxLate: LateReport = {
  year: 2026,
  generatedAt: AT,
  termLabel: "الدورة 1",
  members: [
    {
      memberRef: "A-4",
      months: [
        "late",
        "late",
        "late",
        "late",
        "late",
        "late",
        "late",
        "late",
        "late",
        "upcoming",
        "upcoming",
        "upcoming",
      ],
      fullName: "الحسن ولد عبد الله",
      groupCode: "A",
      lateMonths: [
        "2026-01",
        "2026-02",
        "2026-03",
        "2026-04",
        "2026-05",
        "2026-06",
        "2026-07",
        "2026-08",
        "2026-09",
      ],
      monthsCount: 9,
      levies: [{ title: "ترميم المسجد" }],
    },
    {
      memberRef: "A-5",
      months: [
        "paid",
        "paid",
        "paid",
        "paid",
        "paid",
        "late",
        "late",
        "late",
        "late",
        "upcoming",
        "upcoming",
        "upcoming",
      ],
      fullName: "المختار ولد محمد",
      groupCode: "A",
      lateMonths: ["2026-06", "2026-07", "2026-08", "2026-09"],
      monthsCount: 4,
      levies: [],
    },
    {
      memberRef: "B-8",
      months: [
        "not_owed",
        "not_owed",
        "not_owed",
        "late",
        "late",
        "late",
        "late",
        "late",
        "late",
        "upcoming",
        "upcoming",
        "upcoming",
      ],
      fullName: "باب ولد عبد الله",
      groupCode: "B",
      lateMonths: ["2026-04", "2026-05", "2026-06", "2026-07", "2026-08", "2026-09"],
      monthsCount: 6,
      levies: [],
    },
    {
      memberRef: "B-11",
      months: [
        "paid",
        "paid",
        "paid",
        "paid",
        "paid",
        "paid",
        "paid",
        "paid",
        "paid",
        "upcoming",
        "upcoming",
        "upcoming",
      ],
      fullName: "عبد الرحمن ولد سيدي",
      groupCode: "B",
      lateMonths: [],
      monthsCount: 0,
      levies: [{ title: "ترميم المسجد" }],
    },
  ],
};

// the demo app's four expenses (src/components/app/fixtures.ts EXPENSES): 127 500 = fxAnnual
export const fxExpenses: ExpensesReport = {
  period: { year: 2026 },
  generatedAt: AT,
  items: [
    {
      spentOn: "2026-09-05",
      category: "other",
      label: "أخرى",
      activityId: 4,
      activity: "أخرى",
      note: "طباعة وتصوير",
      amount: 4_500,
      campaignTitle: null,
      recordedBy: "يحيى",
    },
    {
      spentOn: "2026-08-20",
      category: "sports",
      label: "الفريق الرياضي",
      activityId: 3,
      activity: "الفريق الرياضي",
      note: "كرات وأقمصة للفريق",
      amount: 28_000,
      campaignTitle: null,
      recordedBy: "يحيى",
    },
    {
      spentOn: "2026-08-02",
      category: "honoring",
      label: "تكريم الناجحين",
      activityId: 2,
      activity: "تكريم الناجحين",
      note: "تكريم الناجحين في الباكالوريا",
      amount: 35_000,
      campaignTitle: null,
      recordedBy: "سيدي محمد",
    },
    {
      spentOn: "2026-07-14",
      category: "teaching",
      label: "التدريس المحظري",
      activityId: 1,
      activity: "التدريس المحظري",
      note: "دروس تقوية صيفية",
      amount: 60_000,
      campaignTitle: null,
      recordedBy: "سيدي محمد",
    },
  ],
  byCategory: fxAnnual.spending.byCategory,
  byActivity: fxAnnual.spending.byActivity,
  total: fxAnnual.spending.total,
};

export const fxCampaign: CampaignReport = {
  generatedAt: AT,
  id: "c1",
  title: "ترميم المسجد",
  kind: "donation",
  purpose: "إصلاح سقف المسجد وطلاء الجدران.",
  status: "open",
  targetAmount: 300_000,
  createdAt: "2026-06-01",
  closedAt: null,
  // fxAnnual's donations: 52 000 given, nothing spent yet, all of it still held
  collected: 52_000,
  spent: 0,
  transferred: 0,
  balance: 52_000,
  contributions: [
    { paidOn: "2026-09-20", name: "محمد ولد الشيخ", memberRef: "A-1", amount: 20_000 },
    { paidOn: "2026-08-11", name: "فاعل خير", memberRef: null, amount: 30_000 },
    { paidOn: "2026-06-05", name: "يحيى ولد الشيخ", memberRef: "B-10", amount: 2_000 },
  ],
  expenses: [],
};

export const fxLevy: CampaignReport = {
  generatedAt: AT,
  id: "l1",
  title: "لوحة العيد",
  kind: "levy",
  purpose: null,
  status: "open",
  targetAmount: null,
  createdAt: "2026-05-01",
  closedAt: null,
  // fxAnnual's levies: 3 shares of 10 000 paid, still held (82 000 held = 52 000 + 30 000)
  collected: 30_000,
  spent: 0,
  transferred: 0,
  balance: 30_000,
  contributions: [],
  expenses: [],
  shares: NAMES.slice(0, 5).map((n, i) => ({
    memberRef: `A-${i + 1}`,
    fullName: n,
    expected: 10_000,
    paid: i < 3 ? 10_000 : 0,
    left: i < 3 ? 0 : 10_000,
    exempt: i === 4,
    exemptReason: i === 4 ? "طالب" : null,
  })),
};

export const fxStatement: MemberStatement = {
  generatedAt: AT,
  year: 2026,
  member: {
    memberId: "m1",
    memberRef: "A-5",
    fullName: "المختار ولد محمد",
    groupCode: "A",
    status: "active",
    phone: null,
  },
  months: Array.from({ length: 12 }, (_, k) => ({
    month: k + 1,
    state: k < 5 ? "paid" : k < 9 ? "late" : "upcoming",
    price: 1000,
    paid: k < 5,
    due: k < 9,
  })),
  payments: [
    {
      paymentId: "p1",
      paidOn: "2026-03-02",
      status: "confirmed",
      method: "bankily",
      amount: 3000,
      total: 3000,
      months: ["2026-01", "2026-02", "2026-03"],
      campaigns: [],
      note: null,
      reason: null,
      recordedBy: "سيدي محمد",
      recordedAt: "2026-03-02T09:00:00Z",
      confirmedBy: "يحيى",
      confirmedAt: "2026-03-02T10:00:00Z",
      cancelledBy: null,
      cancelledAt: null,
    },
    {
      paymentId: "p2",
      paidOn: "2026-05-20",
      status: "confirmed",
      method: "cash",
      amount: 2000,
      total: 2000,
      months: ["2026-04", "2026-05"],
      campaigns: [],
      note: null,
      reason: null,
      recordedBy: "يحيى",
      recordedAt: "2026-05-20T09:00:00Z",
      confirmedBy: "يحيى",
      confirmedAt: "2026-05-20T09:00:00Z",
      cancelledBy: null,
      cancelledAt: null,
    },
    {
      paymentId: "p3",
      paidOn: "2026-06-01",
      status: "cancelled",
      method: "cash",
      amount: 1000,
      total: 1000,
      months: ["2026-06"],
      campaigns: [],
      note: null,
      reason: "سُجّلت مرتين",
      recordedBy: "يحيى",
      recordedAt: "2026-06-01T09:00:00Z",
      confirmedBy: null,
      confirmedAt: null,
      cancelledBy: "سيدي محمد",
      cancelledAt: "2026-06-01T12:00:00Z",
    },
  ],
  levies: [{ title: "لوحة العيد", expected: 2000, paid: 0, left: 2000, exempt: false }],
  owed: { monthsCount: 4, amountOwed: 4000, levyLeft: 2000, credit: 0 },
};

export const fxHandover: HandoverReport = {
  generatedAt: AT,
  term: { number: 2, title: "الدورة 2", startedOn: "2026-01-01", endedOn: null },
  opening: fxAnnual.opening,
  income: fxAnnual.income,
  spending: fxAnnual.spending,
  adjustments: 0,
  computedBalance: 376_000,
  // what fxWallets holds
  counted: [
    { label: "بنكيلي", method: "bankily", amount: 180_000 },
    { label: "مصرفي", method: "masrvi", amount: 100_000 },
    { label: "السداد", method: "sedad", amount: 33_500 },
    { label: "نقدًا لدى المسؤول", method: "cash", amount: 62_500 },
  ],
  countedTotal: 376_000,
  difference: 0,
  startedBy: { name: "سيدي محمد", at: "2026-09-28T10:00:00Z" },
  submittedBy: { name: "سيدي محمد", at: null },
  acceptedBy: { name: null, at: null },
  carryOver: ["تبرع «ترميم المسجد» ما زال مفتوحًا.", "لوحة العيد: بقي عضوان لم يدفعا."],
};

// The demo fund's accounts (src/components/app/fixtures.ts ACCOUNTS): same ids and numbers.
const demoAccount = (n: number) => `f0000000-0000-4000-8000-${String(n).padStart(12, "0")}`;

export const fxWallets: WalletsReport = {
  period: { year: 2026 },
  generatedAt: AT,
  // «one pot»: where fxAnnual's money came in (458 500) and went out (the expenses, 127 500)
  wallets: [
    {
      walletTypeId: 1,
      fundAccountId: demoAccount(1),
      method: "bankily",
      label: "بنكيلي",
      logoPath: null,
      accountNumber: "22200000011",
      in: 200_000,
      count: 120,
    },
    {
      walletTypeId: 2,
      fundAccountId: demoAccount(2),
      method: "masrvi",
      label: "مصرفي",
      logoPath: null,
      accountNumber: "22200000012",
      in: 100_000,
      count: 60,
    },
    {
      walletTypeId: 3,
      fundAccountId: demoAccount(3),
      method: "sedad",
      label: "السداد",
      logoPath: null,
      accountNumber: "22200000013",
      in: 33_500,
      count: 20,
    },
  ],
  cash: {
    in: 125_000,
    count: 70,
    out: 127_500,
  },
  totalIn: 458_500,
};

export const fxWork: CommitteeWorkReport = {
  period: { year: 2026 },
  generatedAt: AT,
  people: [
    {
      name: "سيدي محمد",
      isAdmin: true,
      active: true,
      payments: { count: 31, amount: 58_500 },
      expenses: { count: 3, amount: 70_000 },
      cancellations: 1,
      levyExemptions: 1,
      lastAt: AT,
    },
    {
      name: "يحيى",
      isAdmin: false,
      active: true,
      payments: { count: 22, amount: 34_000 },
      expenses: { count: 0, amount: 0 },
      cancellations: 0,
      levyExemptions: 0,
      lastAt: AT,
    },
    {
      name: "المختار",
      isAdmin: false,
      active: false,
      payments: { count: 0, amount: 0 },
      expenses: { count: 0, amount: 0 },
      cancellations: 0,
      levyExemptions: 0,
      lastAt: null,
    },
  ],
  cancelled: [
    {
      what: "دفعة المختار ولد محمد",
      amount: 1000,
      by: "سيدي محمد",
      at: "2026-06-01T12:00:00Z",
      reason: "سُجّلت مرتين",
    },
  ],
};

/* «الإحصاءات»: counts only. 88 active members (A 40, B 48) in September 2026. */
const feeMonths = (year: number, refMonth: number, paid: number[]) =>
  paid.map((n, i) => ({
    month: i + 1,
    active: 88,
    paid: n,
    unpaid: i + 1 <= refMonth ? 88 - n : 0,
  }));
export const fxFeeStats: FeeStats = {
  year: 2026,
  refMonth: 9,
  asOf: null,
  beforeRecords: false,
  overall: { active: 88, paidUp: 42, paidUpPct: 47.7, owe1: 18, owe2to3: 16, owe4plus: 12 },
  groups: [
    { groupCode: "A", active: 40, paidUp: 22, paidUpPct: 55, owe1: 8, owe2to3: 6, owe4plus: 4 },
    { groupCode: "B", active: 48, paidUp: 20, paidUpPct: 41.7, owe1: 10, owe2to3: 10, owe4plus: 8 },
  ],
  months: feeMonths(2026, 9, [80, 78, 76, 74, 70, 66, 60, 52, 42, 5, 2, 2]),
};
export const fxLevyStats: LevyStats = {
  id: "l1",
  title: "لوحة العيد",
  status: "open",
  openedOn: "2026-09-18",
  daysOpen: 12,
  shares: 88,
  paid: 34,
  unpaid: 50,
  exempt: 4,
  paidPct: 40.5,
  expected: 168_000,
  collected: 68_000,
  groups: [
    {
      groupCode: "A",
      shares: 40,
      paid: 20,
      unpaid: 18,
      exempt: 2,
      paidPct: 52.6,
      expected: 76_000,
      collected: 40_000,
    },
    {
      groupCode: "B",
      shares: 48,
      paid: 14,
      unpaid: 32,
      exempt: 2,
      paidPct: 30.4,
      expected: 92_000,
      collected: 28_000,
    },
  ],
};
export const fxDonationStats: DonationStats = {
  id: "c1",
  title: "ترميم المصلى",
  status: "open",
  openedOn: "2026-06-01",
  memberGivers: 22,
  outsideGivers: 5,
  givers: 27,
  activeMembers: 88,
  memberPct: 25,
  collected: 64_000,
  target: 150_000,
  targetPct: 42.7,
};
export const fxStats: StatsReport = {
  period: { year: 2026 },
  generatedAt: AT,
  fees: fxFeeStats,
  previous: {
    ...fxFeeStats,
    year: 2025,
    asOf: "2025-09-30",
    overall: { ...fxFeeStats.overall, paidUp: 48, paidUpPct: 54.5 },
  },
  levies: [fxLevyStats],
  donations: [fxDonationStats],
};
