// Input schemas of the server actions (also usable for client-side form validation).
// Money is integer MRO. Dates are YYYY-MM-DD. Ids of new rows are generated by the client
// (crypto.randomUUID()) so a retried request replays instead of recording twice.
import { z } from "zod";
import { toWesternDigits } from "@/lib/money";
import { Constants } from "@/lib/supabase/database.types";

const E = Constants.public.Enums;

const id = z.uuid();
const mro = z.number().int().positive().max(100_000_000);
const day = z.iso.date();
const text = (max: number) => z.string().trim().min(1).max(max);
const optText = (max: number) =>
  z
    .string()
    .trim()
    .max(max)
    .optional()
    .transform((v) => (v ? v : undefined));
const reason = text(300);
const phone = z
  .string()
  .transform((v) => toWesternDigits(v).replace(/[\s\-.()]/g, ""))
  .pipe(z.string().regex(/^\+?[0-9]{8,15}$/));
const firstOfMonth = day.refine((d) => d.endsWith("-01"), "first day of a month");

const allocationSchema = z.discriminatedUnion("kind", [
  z.object({
    kind: z.literal("months"),
    memberId: id,
    year: z.number().int().min(2020).max(2100),
    month: z.number().int().min(1).max(12),
    amount: mro,
  }),
  z.object({ kind: z.literal("campaign"), campaignId: id, memberId: id.nullish(), amount: mro }),
  z.object({ kind: z.literal("credit"), memberId: id, amount: mro }),
]);

export const recordPaymentSchema = z
  .object({
    id,
    payerName: text(120),
    // 'credit' payments are made by applyCredit only
    method: z.enum(E.payment_method).refine((m) => m !== "credit"),
    amount: mro,
    paidOn: day,
    allocations: z.array(allocationSchema).min(1).max(60),
    txnRef: optText(40),
    proofPath: optText(200),
    proofHash: z
      .string()
      .regex(/^[0-9a-f]{64}$/i)
      .optional(),
    note: optText(500),
  })
  .refine((p) => p.allocations.reduce((s, a) => s + a.amount, 0) === p.amount, {
    message: "allocations_mismatch",
    path: ["allocations"],
  });

export const paymentIdSchema = z.object({ id });
export const idReasonSchema = z.object({ id, reason });

export const recordExpenseSchema = z.object({
  id,
  spentOn: day,
  category: z.enum(E.expense_category),
  amount: mro,
  note: optText(500),
  campaignId: id.optional(),
  receiptPath: optText(200),
});

export const logReminderSchema = z.object({
  kind: z.enum(E.reminder_kind),
  memberId: id.optional(),
  campaignId: id.optional(),
  paymentId: id.optional(),
});

/** Statuses the committee sets (نشط، معفى، غادر); the enum's "away" and "deceased" are not offered. */
const settableStatus = z.enum(["active", "exempt", "left"]);
const listCode = z
  .string()
  .trim()
  .toUpperCase()
  .regex(/^[A-Z]$/);

export const addMemberSchema = z.object({
  listCode,
  number: z.number().int().positive().max(100_000),
  fullName: text(120),
  groupCode: z.string().regex(/^[A-Z]$/),
  fromMonth: firstOfMonth,
  phone: phone.optional(),
  note: optText(500),
  status: settableStatus.default("active"),
});

export const updateMemberSchema = z.object({
  memberId: id,
  fullName: text(120),
  phone: phone.nullable(),
  note: z.string().trim().max(500).nullable(),
  /** new number in the same list; omit to keep */
  number: z.number().int().positive().max(100_000).optional(),
});

export const changeMemberStatusSchema = z.object({
  memberId: id,
  fromMonth: firstOfMonth,
  status: settableStatus,
  reason,
  groupCode: z
    .string()
    .regex(/^[A-Z]$/)
    .optional(),
});

/** Undo the member's last status/group change (admin; refused over paid or pending months). */
export const cancelLastPeriodSchema = z.object({ memberId: id, reason });

/** Correct the month the member joined (admin; refused past paid or pending months). */
export const setJoinMonthSchema = z.object({ memberId: id, fromMonth: firstOfMonth, reason });

/** Pay months of one member from their credit (confirmers). */
export const applyCreditSchema = z.object({
  id,
  memberId: id,
  months: z
    .array(
      z.object({
        year: z.number().int().min(2000).max(2100),
        month: z.number().int().min(1).max(12),
      }),
    )
    .min(1)
    .max(60),
});

export const changeMemberGroupSchema = z.object({
  memberId: id,
  fromMonth: firstOfMonth,
  groupCode: z.string().regex(/^[A-Z]$/),
  reason: optText(300),
});
export type ChangeMemberGroupInput = z.input<typeof changeMemberGroupSchema>;

export const setGroupPriceSchema = z.object({
  groupCode: z.string().regex(/^[A-Z]$/),
  year: z.number().int().min(2020).max(2100),
  monthlyAmount: mro,
});

export const setCommitteeMemberSchema = z.object({
  userId: id,
  displayName: text(80),
  role: z.enum(E.committee_role),
  /** required: null UNLINKS (the database stores exactly this value) */
  memberId: id.nullable(),
  active: z.boolean().default(true),
});

export const updateSettingsSchema = z.object({
  openingBalance: z.number().int().min(0).max(1_000_000_000).optional(),
  openingBalanceOn: day.optional(),
  graceDays: z.number().int().min(0).max(27).optional(),
  showAmountOwed: z.boolean().optional(),
  /** "" clears the contact; undefined leaves it as is */
  whatsappContact: z.union([z.literal(""), phone]).optional(),
});

const NOT_WALLETS: readonly string[] = ["cash", "paper", "other", "credit"];

export const addFundAccountSchema = z.object({
  method: z.enum(E.payment_method).refine((m) => !NOT_WALLETS.includes(m), "not_a_wallet"),
  accountNumber: z
    .string()
    .transform((v) => toWesternDigits(v).replace(/[\s-]/g, ""))
    .pipe(z.string().regex(/^[0-9A-Za-z+]{4,30}$/)),
  holderName: text(120),
  note: optText(300),
  sortOrder: z.number().int().min(0).max(1000).default(0),
});

export const updateFundAccountSchema = z.object({
  id,
  holderName: text(120),
  note: z.string().trim().max(300).nullable(),
  sortOrder: z.number().int().min(0).max(1000),
  active: z.boolean(),
});

export const createCampaignSchema = z.object({
  id,
  title: text(120),
  amountMode: z.enum(E.campaign_mode).default("open"),
  purpose: optText(500),
  targetAmount: mro.optional(),
  deadline: day.optional(),
  participants: z
    .array(z.object({ memberId: id, expectedAmount: mro.nullable() }))
    .max(500)
    .optional(),
});

export const updateCampaignSchema = z.object({
  id,
  title: text(120),
  purpose: z.string().trim().max(500).nullable(),
  targetAmount: mro.nullable(),
  deadline: day.nullable(),
});

export const closeCampaignSchema = z.object({ id, surplusAction: z.enum(E.surplus_action) });

export type CreateCampaignInput = z.input<typeof createCampaignSchema>;
export type UpdateCampaignInput = z.input<typeof updateCampaignSchema>;
export type CloseCampaignInput = z.input<typeof closeCampaignSchema>;

const countedLine = z.object({
  label: text(80),
  method: z.enum(E.payment_method).nullish(),
  accountId: id.nullish(),
  amount: z.number().int().min(0).max(1_000_000_000),
});

export const startHandoverSchema = z.object({ id, note: optText(500) });
export const updateHandoverDraftSchema = z.object({
  id,
  countedLines: z.array(countedLine).max(50),
  carryOver: z.array(id).max(50).default([]),
  note: optText(500),
});
export const acceptHandoverSchema = z.object({ id, newTermTitle: optText(80) });
export const cancelHandoverSchema = z.object({ id, reason });

export type StartHandoverInput = z.input<typeof startHandoverSchema>;
export type UpdateHandoverDraftInput = z.input<typeof updateHandoverDraftSchema>;
export type AcceptHandoverInput = z.input<typeof acceptHandoverSchema>;
export type CancelHandoverInput = z.input<typeof cancelHandoverSchema>;

export const passwordSchema = z.object({ password: z.string().min(8).max(72) });

export const createCommitteeAccountSchema = z.object({
  displayName: text(80),
  /** email or phone number; checked with parseLogin() */
  login: z.string().trim().min(3).max(120),
  role: z.enum(E.committee_role),
  memberId: id.nullish(),
});
export const committeeUserSchema = z.object({ userId: id });
export const setCommitteeActiveSchema = z.object({ userId: id, active: z.boolean() });

export type CreateCommitteeAccountInput = z.input<typeof createCommitteeAccountSchema>;
export type SetCommitteeActiveInput = z.input<typeof setCommitteeActiveSchema>;
export type RecordPaymentInput = z.input<typeof recordPaymentSchema>;
export type AllocationInput = z.input<typeof allocationSchema>;
export type RecordExpenseInput = z.input<typeof recordExpenseSchema>;
export type LogReminderInput = z.input<typeof logReminderSchema>;
export type AddMemberInput = z.input<typeof addMemberSchema>;
export type UpdateMemberInput = z.input<typeof updateMemberSchema>;
export type ChangeMemberStatusInput = z.input<typeof changeMemberStatusSchema>;
export type ApplyCreditInput = z.input<typeof applyCreditSchema>;
export type CancelLastPeriodInput = z.input<typeof cancelLastPeriodSchema>;
export type SetJoinMonthInput = z.input<typeof setJoinMonthSchema>;
export type SetGroupPriceInput = z.input<typeof setGroupPriceSchema>;
export type SetCommitteeMemberInput = z.input<typeof setCommitteeMemberSchema>;
export type UpdateSettingsInput = z.input<typeof updateSettingsSchema>;
export type AddFundAccountInput = z.input<typeof addFundAccountSchema>;
export type UpdateFundAccountInput = z.input<typeof updateFundAccountSchema>;

/** PushSubscription.toJSON() from the browser. */
export const pushSubscriptionSchema = z.object({
  endpoint: z.url({ protocol: /^https$/ }).max(1000),
  keys: z.object({
    p256dh: z.string().min(20).max(200),
    auth: z.string().min(8).max(100),
  }),
  userAgent: z.string().max(300).optional(),
});
export const pushEndpointSchema = z.object({ endpoint: z.string().min(1).max(1000) });
export type PushSubscriptionInput = z.input<typeof pushSubscriptionSchema>;

export const updateMyProfileSchema = z.object({
  displayName: z.string().trim().min(1).max(60),
  memberId: id.nullable().optional(),
});
export type UpdateMyProfileInput = z.input<typeof updateMyProfileSchema>;
export const signOutEverywhereSchema = z.object({ endpoint: z.string().max(1000).optional() });

export const completeSetupSchema = z.object({
  displayName: z.string().trim().min(1).max(60),
  /** null = «لست عضوًا» */
  memberId: id.nullable(),
  password: z.string().min(8).max(72),
});
export type CompleteSetupInput = z.input<typeof completeSetupSchema>;

export const linkCommitteeMemberSchema = z.object({ userId: id, memberId: id.nullable() });
export type LinkCommitteeMemberInput = z.input<typeof linkCommitteeMemberSchema>;
